TP3
tienslebienz/tp-alexis pull request #2
Opened 2018-01-15 15:37 UTC by albrones

Tests added for TP3

2018-01-16 09:51 UTC, tienslebienz commented
Premières remarques avant de regarder le contenu de la PR : 
* Tu n'as pas créé de branche pour ton développement, même si ce n'est pas nécessaire pour faire une PR, c'est une habitude à prendre
* Il y a des conflits à résoudre

2018-01-16 09:56 UTC, tienslebienz commented
Quand tu résoudras les conflits, je ne veux pas voir de commit `merge from master`. IE utilise `git rebase`

2018-01-16 10:15 UTC, tienslebienz requested changes

2018-01-16 10:15 UTC, tienslebienz commented on .gitignore
> +.idea
Personnellement, je ne suis pas fan.
À mon sens c'est de l'ordre de la configuration perso.
Mais c'est vrai que ça simplifie la vie à tout le monde donc tu peux laisser

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.js
> +  this.toString = this.toString() + " niveau: " + this.niveauScolaire;
To string n'est plus une fonction, si tu changes un des paramètres après l’initialisation, toString ne sera plus pertinent.

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.js
> + this.toString = this.toString() + " permis: " + this.permis;
Idem

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.js
> +    Adulte: Adulte,
Petite remarque, c'est très bien de reformatter le code.
Par contre, ça pollue un peu la PR.
Une bonne pratique, est de faire un commit « style » dans lequel tu ne change rien fonctionnellement parlant mais où tu fais toutes tes modification de style (indentation, découpage de ligne…)
Ainsi, lors de la revue, je ne regarde que les commits pertinents.

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.js
> -//Si on remplace tout par les this des props par var on obtient que des [object Object] soit des objets "undefined"
Même principe, ça ne concerne pas ton commit `Add test`, tu aurais plutôt dû faire un commit pour ça.
Les commits, ça ne coûte rien avec git, il ne faut pas être radin. ceux qui regardent uniquement le diff global ne verront pas la différence, ceux qui regarde commit par commit apprécieront, on regarde le titre du commit et on sait tout de suite si ce que tu as fait correspond à ton message

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.spec.js
> +    });
Plutôt que `.toBeDefined`, teste `.toBe('B')` etc

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.spec.js
> +    });
C'est encore une préférence personnelle, mais je préfère `.toBe()` à `.toEqual()` quand c'est possible.
Fais-tu la différence entre ces deux méthodes ?

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.spec.js
> +      });
Idem plutôt que `.toBeDefined` on préférera `.toBe('Zen')`

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.spec.js
> +      });
Il faudrait également tester les autres propriétés.

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.spec.js
> +      });
C'est ce que je disais dans ton code, tu dis que tu testes une méthode (ce qui devrait être le cas).
Hors tu ne testes qu'une propriété.

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.spec.js
> +      });
Dans une approche TDD, pour corriger ce bug il faudrait rajouter un test
```js
it('should have toString method with niveau scolaire prop', function () {
    var enfant = new Enfant('B','A', 22, 'ZEN');
    enfant.niveauScolaire = 'zenika';
    expect(enfant.toString()).toEqual("B A 22 niveau: zenika");
});
```

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.spec.js
> +      });
idem enfant

2018-01-16 10:15 UTC, tienslebienz commented on src/tp3.spec.js
> +      });
Idem enfant

2018-01-16 10:22 UTC, tienslebienz commented
Je te remet également les consignes que je t'avais envoyé par mail mise à jour
Quelques ajout sur ce TP :
* Utiliser des prototypes pour la méthode `toString`
* Question: « Qu'apporte l'utilisation des prototypes ? »
* Fais en sorte que `age` ne soit pas accessible et ajoute 2 méthodes `getAge()` et `setAge()` pour le mettre à jour
* Faire que le nom soit accessible en lecture mais pas en écriture
o```js
personne.name // toto
personne.name = 'tata';
personne.name // toto
```

2018-01-16 19:18 UTC, tienslebienz commented
BTW si tu n'es pas d'accord avec certains points on peut en discuter, n'hésite pas à répondre à mes remarques.

2018-01-17 09:42 UTC, albrones commented on .gitignore
> +.idea
Quelle serait la bonne pratique alors ?

2018-01-17 12:46 UTC, tienslebienz commented on .gitignore
> +.idea
https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

2018-01-18 09:18 UTC, albrones commented on src/tp3.spec.js
> +    });
Si j'ai bien compris toBe vérifie la valeur et la référence si il y en a une alors que toEqual vérifie seulement la valeur

2018-01-18 11:05 UTC, albrones commented on src/tp3.js
> +  this.toString = this.toString() + " niveau: " + this.niveauScolaire;
Le fait d'utiliser un prototype permet de faire de l'héritage pour surcharger la méthode toString()

2018-01-18 12:35 UTC, tienslebienz commented on src/tp3.spec.js
> +    });
en fait `.toBe` ne vérifie même que la référence. Si c'est la même référence, c'est la même valeur.
Mais oui, c'est ça.

2018-01-18 12:36 UTC, tienslebienz commented on .gitignore
> +.idea
Mais encore une fois, tu peux le garder, tout le monde le fait, c'est plus simple pour tout le monde.

2018-01-18 13:04 UTC, tienslebienz commented on src/tp3.js
> +  this.toString = this.toString() + " niveau: " + this.niveauScolaire;
Pour le vocabulaire, la surcharge c'est quand tu as un même nom de méthode, mais différent comportement selon les paramêtres. On peut imiter ce comportement grâce à la variable [`arguments`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Fonctions/arguments) ou avec le [`rest parameter`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Fonctions/param%C3%A8tres_du_reste) avec la norme es2015.
Tu voulais sans doute parler de polymorphisme, mais on peut imiter ce comportement sans prototypes.
```javascript
function A() {
  this.fn = () => console.log('A');
}

function B() {
  A.call(this);
  var aFn = this.fn;
  this.fn = () => aFn() || console.log('B');
}

var b = new B();
b.fn();
```

2018-01-18 15:44 UTC, albrones commented
J'ai fait toutes les motifs dans une branche TP3 et resetant la master à l'état initial. 
Mais là je ne sais pas ce que je dois faire avec la PR. 
J'ai essayé de résoudre le conflit et ça m'a seulement fait un commit de merge ...

2018-01-18 15:47 UTC, tienslebienz commented
Tu peux fermer cette PR et en ouvrir une nouvelle à partir de ta nouvelle branche

2018-01-18 15:48 UTC, closed without merging